package com.example.app.activitylog;

public enum ActivityAction {
    SESSION_CREATED,
    SESSION_UPDATED,
    SESSION_RESCHEDULED,
    SESSION_CANCELLED,
    SESSION_DELETED,
    SESSION_PARTICIPANT_ADDED,
    SESSION_PARTICIPANT_REMOVED,

    CLIENT_CREATED,
    CLIENT_UPDATED,
    CLIENT_DELETED,
    CLIENT_ANONYMIZED,
    CLIENT_DEACTIVATED,
    CLIENT_ACTIVATED,

    INVOICE_CREATED,
    INVOICE_PAID,
    INVOICE_REFUNDED,
    INVOICE_SENT,
    OPEN_BILL_CREATED,
    OPEN_BILL_UPDATED,
    ENTITLEMENT_USED,

    MESSAGE_SENT,
    MESSAGE_SCHEDULED,
    MESSAGE_SCHEDULE_CANCELLED,
    INTERNAL_NOTE_ADDED,
    GROUP_MESSAGE_SENT,
    GROUP_MESSAGE_SCHEDULED
}
