-- Calendra clean pre-production Flyway baseline schema.
-- Generated by squashing the previous pre-production migration chain into one V1 migration.
-- Use only on a database that has been reset before production, for example with `docker compose down -v`.
-- After real production launch, do not edit this file; add V2, V3, ... migrations instead.



-- ============================================================================
-- Squashed from V3__baseline_schema.sql
-- ============================================================================

-- Full Flyway baseline schema for clean staging/production PostgreSQL databases.
-- This migration is intentionally CREATE TABLE IF NOT EXISTS so it is safe on existing databases that were created before Flyway was introduced.
-- Existing environments should still be validated against a clean staging restore before production launch.

-- backend/src/main/java/com/example/app/admin/PlatformTenancyAdminAuditLog.java
CREATE TABLE IF NOT EXISTS platform_tenancy_admin_audit_logs (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    actor_user_id BIGINT NOT NULL,
    action_type VARCHAR(64) NOT NULL,
    summary VARCHAR(500) NOT NULL,
    detail TEXT,
    reason TEXT
);

-- backend/src/main/java/com/example/app/auth/PasswordResetToken.java
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id BIGINT NOT NULL,
    token VARCHAR(128) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    active BOOLEAN NOT NULL
);

-- backend/src/main/java/com/example/app/auth/SignupEmailIntent.java
CREATE TABLE IF NOT EXISTS signup_email_intents (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    token VARCHAR(128) NOT NULL,
    email VARCHAR(255) NOT NULL,
    payload_json TEXT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    active BOOLEAN NOT NULL
);

-- backend/src/main/java/com/example/app/billing/AdvanceAllocation.java
CREATE TABLE IF NOT EXISTS advance_allocations (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    advance_bill_id BIGINT NOT NULL,
    open_bill_id BIGINT NOT NULL,
    session_booking_id BIGINT NOT NULL,
    transaction_service_id BIGINT NOT NULL,
    amount_net NUMERIC(19, 4) NOT NULL
);

-- backend/src/main/java/com/example/app/billing/Bill.java
CREATE TABLE IF NOT EXISTS bills (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    bill_number VARCHAR(255) NOT NULL,
    order_id VARCHAR(160),
    order_counter BIGINT,
    bill_type VARCHAR(16) NOT NULL,
    client_id BIGINT,
    client_first_name_snapshot VARCHAR(255) NOT NULL,
    client_last_name_snapshot VARCHAR(255) NOT NULL,
    recipient_type_snapshot VARCHAR(255),
    recipient_person_email_snapshot VARCHAR(255),
    recipient_company_id_snapshot BIGINT,
    recipient_company_name_snapshot VARCHAR(255),
    recipient_company_address_snapshot VARCHAR(255),
    recipient_company_postal_code_snapshot VARCHAR(255),
    recipient_company_city_snapshot VARCHAR(255),
    recipient_company_vat_id_snapshot VARCHAR(255),
    recipient_company_iban_snapshot VARCHAR(255),
    recipient_company_email_snapshot VARCHAR(255),
    recipient_company_telephone_snapshot VARCHAR(255),
    source_session_id_snapshot BIGINT,
    payment_method_id BIGINT,
    consultant_id BIGINT NOT NULL,
    issue_date DATE NOT NULL,
    total_net NUMERIC(19, 4) NOT NULL,
    total_gross NUMERIC(19, 4) NOT NULL,
    payment_status VARCHAR(255) NOT NULL,
    checkout_session_id VARCHAR(255),
    checkout_session_expires_at TIMESTAMP WITH TIME ZONE,
    payment_intent_id VARCHAR(255),
    stripe_connected_account_id VARCHAR(255),
    stripe_connect_mode VARCHAR(32),
    stripe_customer_id VARCHAR(255),
    stripe_invoice_id VARCHAR(255),
    stripe_invoice_number VARCHAR(255),
    stripe_bank_transfer_iban VARCHAR(255),
    stripe_bank_transfer_bic VARCHAR(255),
    stripe_bank_transfer_account_holder_name VARCHAR(255),
    stripe_bank_transfer_account_holder_address_line1 VARCHAR(255),
    stripe_bank_transfer_account_holder_postal_code VARCHAR(255),
    stripe_bank_transfer_account_holder_city VARCHAR(255),
    stripe_bank_transfer_account_holder_country VARCHAR(255),
    stripe_bank_transfer_reference VARCHAR(255),
    bank_transfer_reference VARCHAR(255),
    refund_of_bill_id BIGINT,
    refund_reference VARCHAR(255),
    stripe_hosted_invoice_url VARCHAR(2048),
    paid_at TIMESTAMP WITH TIME ZONE,
    fiscal_status VARCHAR(255) NOT NULL,
    fiscal_zoi VARCHAR(255),
    fiscal_eor VARCHAR(255),
    fiscal_qr TEXT,
    fiscal_sent_at TIMESTAMP WITH TIME ZONE,
    fiscal_message_id VARCHAR(255),
    fiscal_attempt_count INTEGER,
    fiscal_last_error TEXT,
    fiscal_log_json TEXT,
    fiscal_request_body TEXT,
    fiscal_response_body TEXT,
    invoice_pdf_object_key VARCHAR(1024),
    invoice_locale VARCHAR(8)
);

-- backend/src/main/java/com/example/app/billing/BillItem.java
CREATE TABLE IF NOT EXISTS bill_item (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    bill_id BIGINT NOT NULL,
    transaction_service_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    net_price NUMERIC(19, 4) NOT NULL,
    gross_price NUMERIC(19, 4) NOT NULL,
    invoice_line_description VARCHAR(512),
    source_session_booking_id BIGINT,
    source_advance_bill_id BIGINT
);

-- backend/src/main/java/com/example/app/billing/BillPayment.java
CREATE TABLE IF NOT EXISTS bill_payments (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    bill_id BIGINT NOT NULL,
    payment_method_id BIGINT NOT NULL,
    amount_gross NUMERIC(19, 4) NOT NULL,
    sort_order INTEGER NOT NULL,
    source_advance_bill_id BIGINT
);

-- backend/src/main/java/com/example/app/billing/OpenBill.java
CREATE TABLE IF NOT EXISTS open_bills (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    consultant_id BIGINT NOT NULL,
    payment_method_id BIGINT,
    reference VARCHAR(255),
    session_booking_id BIGINT,
    batch_scope VARCHAR(16) NOT NULL,
    batch_target_client_id BIGINT,
    batch_target_company_id BIGINT,
    manual_split_locked BOOLEAN NOT NULL,
    manual_session_numbers_csv VARCHAR(255),
    manual_session_number_max BIGINT,
    bill_type VARCHAR(16),
    booking_group_key VARCHAR(64),
    discount_type VARCHAR(16),
    discount_value NUMERIC(19, 4),
    discount_item_index INTEGER,
    whole_bill_discount_percent NUMERIC(19, 4),
    item_discounts_json TEXT,
    proforma_number VARCHAR(80),
    proforma_sequence_number BIGINT,
    source_guest_order_id BIGINT
);

-- backend/src/main/java/com/example/app/billing/OpenBillItem.java
CREATE TABLE IF NOT EXISTS open_bill_items (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    open_bill_id BIGINT NOT NULL,
    transaction_service_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    net_price NUMERIC(19, 4) NOT NULL,
    unit_gross_price NUMERIC(19, 4),
    invoice_line_description VARCHAR(512),
    source_session_booking_id BIGINT,
    source_advance_bill_id BIGINT
);

-- backend/src/main/java/com/example/app/billing/OpenBillPayment.java
CREATE TABLE IF NOT EXISTS open_bill_payments (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    open_bill_id BIGINT NOT NULL,
    payment_method_id BIGINT NOT NULL,
    amount_gross NUMERIC(19, 4) NOT NULL,
    sort_order INTEGER NOT NULL,
    source_advance_bill_id BIGINT
);

-- backend/src/main/java/com/example/app/billing/PaymentMethod.java
CREATE TABLE IF NOT EXISTS payment_methods (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    payment_type VARCHAR(255) NOT NULL,
    fiscalized BOOLEAN NOT NULL,
    stripe_enabled BOOLEAN NOT NULL,
    guest_enabled BOOLEAN NOT NULL,
    widget_enabled BOOLEAN NOT NULL,
    guest_display_order INTEGER NOT NULL,
    allowed_guest_product_types_json VARCHAR(255)
);

-- backend/src/main/java/com/example/app/billing/TransactionService.java
CREATE TABLE IF NOT EXISTS transaction_service (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    code VARCHAR(12) NOT NULL,
    description VARCHAR(255) NOT NULL,
    tax_rate VARCHAR(255) NOT NULL,
    net_price NUMERIC(19, 4) NOT NULL,
    active BOOLEAN NOT NULL
);

-- backend/src/main/java/com/example/app/client/Client.java
CREATE TABLE IF NOT EXISTS clients (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    slovenian_locale VARCHAR(255),
    company_id BIGINT NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(255),
    whatsapp_phone VARCHAR(255),
    whatsapp_opt_in BOOLEAN NOT NULL,
    viber_user_id VARCHAR(255),
    viber_connected BOOLEAN NOT NULL,
    anonymized BOOLEAN NOT NULL,
    anonymized_at TIMESTAMP WITH TIME ZONE,
    anonymized_by_user_id BIGINT,
    active BOOLEAN NOT NULL,
    batch_payment_enabled BOOLEAN NOT NULL,
    inbox_starred BOOLEAN NOT NULL,
    inbox_closed BOOLEAN NOT NULL,
    assigned_to_id BIGINT,
    billing_company_id BIGINT,
    invoice_recipient_type VARCHAR(16) NOT NULL,
    invoice_person_address_line VARCHAR(255),
    invoice_person_postal_code VARCHAR(255),
    invoice_person_city VARCHAR(255),
    invoice_company_name VARCHAR(255),
    invoice_company_address_line VARCHAR(255),
    invoice_company_postal_code VARCHAR(255),
    invoice_company_city VARCHAR(255),
    invoice_company_vat_id VARCHAR(255)
);

-- backend/src/main/java/com/example/app/client/PreferredSlot.java
CREATE TABLE IF NOT EXISTS preferred_slot (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    client_id BIGINT NOT NULL,
    day_of_week VARCHAR(255),
    start_time TIME,
    end_time TIME
);

-- backend/src/main/java/com/example/app/company/ClientCompany.java
CREATE TABLE IF NOT EXISTS client_companies (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    owner_company_id BIGINT NOT NULL,
    platform_tenant_company_id BIGINT,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    postal_code VARCHAR(255),
    city VARCHAR(255),
    vat_id VARCHAR(255),
    iban VARCHAR(255),
    email VARCHAR(255),
    telephone VARCHAR(255),
    active BOOLEAN NOT NULL,
    batch_payment_enabled BOOLEAN NOT NULL
);

-- backend/src/main/java/com/example/app/company/Company.java
CREATE TABLE IF NOT EXISTS company (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    name VARCHAR(255) NOT NULL,
    tenant_code VARCHAR(64),
    paypal_merchant_id VARCHAR(255),
    paypal_tracking_id VARCHAR(255),
    paypal_onboarding_status VARCHAR(64),
    paypal_payments_receivable BOOLEAN,
    paypal_primary_email_confirmed BOOLEAN
);

-- backend/src/main/java/com/example/app/consumables/Consumable.java
CREATE TABLE IF NOT EXISTS consumable (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    category_id BIGINT,
    name VARCHAR(160) NOT NULL,
    description TEXT,
    sku VARCHAR(80),
    barcode VARCHAR(80),
    unit VARCHAR(32) NOT NULL,
    location VARCHAR(120),
    current_stock NUMERIC(19, 4) NOT NULL,
    minimum_stock NUMERIC(19, 4) NOT NULL,
    cost_price NUMERIC(19, 4) NOT NULL,
    sale_price NUMERIC(19, 4),
    vat_rate_id BIGINT,
    track_stock BOOLEAN NOT NULL,
    billable BOOLEAN NOT NULL,
    active BOOLEAN NOT NULL
);

-- backend/src/main/java/com/example/app/consumables/ConsumableCategory.java
CREATE TABLE IF NOT EXISTS consumable_category (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    color VARCHAR(32),
    active BOOLEAN NOT NULL
);

-- backend/src/main/java/com/example/app/consumables/ConsumablePurchaseOrder.java
CREATE TABLE IF NOT EXISTS consumable_purchase_order (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    order_number VARCHAR(64) NOT NULL,
    supplier_id BIGINT,
    status VARCHAR(32) NOT NULL,
    order_date DATE,
    expected_date DATE,
    total_amount NUMERIC(19, 4) NOT NULL,
    received_amount NUMERIC(19, 4) NOT NULL,
    notes TEXT
);

-- backend/src/main/java/com/example/app/consumables/ConsumableStockMovement.java
CREATE TABLE IF NOT EXISTS consumable_stock_movement (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    consumable_id BIGINT NOT NULL,
    movement_type VARCHAR(40) NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    source_id BIGINT,
    quantity_delta NUMERIC(19, 4) NOT NULL,
    stock_before NUMERIC(19, 4) NOT NULL,
    stock_after NUMERIC(19, 4) NOT NULL,
    unit_cost_snapshot NUMERIC(19, 4) NOT NULL,
    value_delta NUMERIC(19, 4),
    note TEXT,
    created_by_id BIGINT
);

-- backend/src/main/java/com/example/app/consumables/ConsumableSupplier.java
CREATE TABLE IF NOT EXISTS consumable_supplier (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    name VARCHAR(180) NOT NULL,
    contact_name VARCHAR(160),
    phone VARCHAR(80),
    email VARCHAR(180),
    categories VARCHAR(255),
    payment_terms_days INTEGER NOT NULL,
    reliability_percent INTEGER NOT NULL,
    outstanding_amount NUMERIC(19, 4),
    status VARCHAR(24) NOT NULL
);

-- backend/src/main/java/com/example/app/consumables/ServiceTypeConsumable.java
CREATE TABLE IF NOT EXISTS service_type_consumable (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    session_type_id BIGINT NOT NULL,
    consumable_id BIGINT NOT NULL,
    default_quantity NUMERIC(19, 4) NOT NULL,
    quantity_mode VARCHAR(32) NOT NULL,
    billable_override BOOLEAN,
    notes TEXT
);

-- backend/src/main/java/com/example/app/consumables/SessionConsumable.java
CREATE TABLE IF NOT EXISTS session_consumable (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    session_booking_id BIGINT NOT NULL,
    booking_group_key VARCHAR(64) NOT NULL,
    service_type_id BIGINT,
    consumable_id BIGINT NOT NULL,
    quantity NUMERIC(19, 4) NOT NULL,
    unit VARCHAR(32) NOT NULL,
    quantity_mode VARCHAR(32) NOT NULL,
    cost_price_snapshot NUMERIC(19, 4) NOT NULL,
    sale_price_snapshot NUMERIC(19, 4),
    billable BOOLEAN NOT NULL,
    source VARCHAR(32) NOT NULL,
    manually_changed BOOLEAN NOT NULL,
    notes TEXT
);

-- backend/src/main/java/com/example/app/course/Course.java
CREATE TABLE IF NOT EXISTS courses (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    guest_product_id BIGINT,
    title VARCHAR(180) NOT NULL,
    description TEXT,
    media_type VARCHAR(16) NOT NULL,
    status VARCHAR(24) NOT NULL,
    price_gross NUMERIC(19, 4) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    active BOOLEAN NOT NULL,
    guest_visible BOOLEAN NOT NULL,
    sort_order INTEGER NOT NULL,
    thumbnail_url VARCHAR(512),
    bunny_library_id VARCHAR(96),
    bunny_library_name VARCHAR(180),
    bunny_video_id VARCHAR(96),
    bunny_storage_path VARCHAR(512),
    bunny_cdn_url VARCHAR(512),
    duration_seconds INTEGER,
    file_name VARCHAR(255),
    content_type VARCHAR(120),
    metadata_json TEXT
);

-- backend/src/main/java/com/example/app/course/MembershipCourse.java
CREATE TABLE IF NOT EXISTS membership_courses (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    membership_product_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL
);

-- backend/src/main/java/com/example/app/files/ClientFile.java
CREATE TABLE IF NOT EXISTS client_files (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    client_id BIGINT NOT NULL,
    owner_company_id BIGINT NOT NULL,
    original_file_name VARCHAR(512) NOT NULL,
    content_type VARCHAR(255),
    size_bytes BIGINT NOT NULL,
    s3_object_key VARCHAR(1024) NOT NULL,
    uploaded_by_user_id BIGINT,
    uploaded_by_guest_user_id BIGINT,
    pending_inbox_attachment BOOLEAN NOT NULL
);

-- backend/src/main/java/com/example/app/files/CompanyFile.java
CREATE TABLE IF NOT EXISTS company_files (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    owner_company_id BIGINT NOT NULL,
    original_file_name VARCHAR(512) NOT NULL,
    content_type VARCHAR(255),
    size_bytes BIGINT NOT NULL,
    s3_object_key VARCHAR(1024) NOT NULL,
    uploaded_by_user_id BIGINT
);

-- backend/src/main/java/com/example/app/fiscal/FiscalCertificate.java
CREATE TABLE IF NOT EXISTS fiscal_certificates (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    certificate_data_bytes BYTEA
);

-- backend/src/main/java/com/example/app/google/GoogleOAuthToken.java
CREATE TABLE IF NOT EXISTS google_oauth_tokens (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    access_token VARCHAR(2000) NOT NULL,
    refresh_token VARCHAR(2000),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- backend/src/main/java/com/example/app/google/calendar/GoogleCalendarConnection.java
CREATE TABLE IF NOT EXISTS google_calendar_connections (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    user_id BIGINT,
    google_account_email VARCHAR(512),
    calendar_id VARCHAR(1024) NOT NULL,
    calendar_summary VARCHAR(512),
    sync_direction VARCHAR(32) NOT NULL,
    allow_google_to_modify_bookings BOOLEAN NOT NULL,
    booking_delete_policy VARCHAR(32) NOT NULL,
    import_google_events_as VARCHAR(32) NOT NULL,
    access_token VARCHAR(4000) NOT NULL,
    refresh_token VARCHAR(4000),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    scopes VARCHAR(1000),
    sync_token VARCHAR(4000),
    channel_id VARCHAR(128),
    resource_id VARCHAR(512),
    channel_expires_at TIMESTAMP WITH TIME ZONE,
    last_full_sync_at TIMESTAMP WITH TIME ZONE,
    last_incremental_sync_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(32) NOT NULL,
    last_error VARCHAR(2000)
);

-- backend/src/main/java/com/example/app/google/calendar/GoogleCalendarEventLink.java
CREATE TABLE IF NOT EXISTS google_calendar_event_links (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    connection_id BIGINT NOT NULL,
    calendar_id VARCHAR(1024) NOT NULL,
    google_event_id VARCHAR(1024) NOT NULL,
    google_etag VARCHAR(512),
    google_ical_uid VARCHAR(512),
    google_updated_at TIMESTAMP WITH TIME ZONE,
    app_entity_type VARCHAR(32) NOT NULL,
    app_entity_id BIGINT NOT NULL,
    origin VARCHAR(20) NOT NULL,
    sync_status VARCHAR(32) NOT NULL,
    last_error VARCHAR(2000),
    last_synced_hash VARCHAR(128),
    last_synced_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE
);

-- backend/src/main/java/com/example/app/google/calendar/GoogleCalendarSyncJob.java
CREATE TABLE IF NOT EXISTS google_calendar_sync_jobs (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    connection_id BIGINT,
    app_entity_type VARCHAR(32),
    app_entity_id BIGINT,
    action VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempts INTEGER NOT NULL,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_error VARCHAR(2000)
);

-- backend/src/main/java/com/example/app/group/ClientGroup.java
CREATE TABLE IF NOT EXISTS client_groups (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    active BOOLEAN NOT NULL,
    batch_payment_enabled BOOLEAN NOT NULL,
    individual_payment_enabled BOOLEAN NOT NULL,
    billing_company_id BIGINT
);

-- backend/src/main/java/com/example/app/guest/auth/GuestPasswordResetToken.java
CREATE TABLE IF NOT EXISTS guest_password_reset_tokens (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    guest_user_id BIGINT NOT NULL,
    token VARCHAR(128) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    verification_code_hash VARCHAR(128),
    failed_attempts INTEGER NOT NULL,
    code_verified_at TIMESTAMP WITH TIME ZONE,
    active BOOLEAN NOT NULL
);

-- backend/src/main/java/com/example/app/guest/model/GuestDeviceToken.java
CREATE TABLE IF NOT EXISTS guest_device_tokens (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    guest_user_id BIGINT NOT NULL,
    platform VARCHAR(16) NOT NULL,
    push_token VARCHAR(512) NOT NULL,
    locale VARCHAR(8),
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_guest_device_tokens_push_token
    ON guest_device_tokens (push_token);
CREATE INDEX IF NOT EXISTS idx_guest_device_tokens_guest_updated
    ON guest_device_tokens (guest_user_id, updated_at DESC);

-- backend/src/main/java/com/example/app/guest/model/GuestEntitlement.java
CREATE TABLE IF NOT EXISTS guest_entitlements (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    source_order_id BIGINT NOT NULL,
    entitlement_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    remaining_uses INTEGER,
    remaining_value_gross NUMERIC(19, 4),
    valid_from TIMESTAMP WITH TIME ZONE NOT NULL,
    valid_until TIMESTAMP WITH TIME ZONE,
    entitlement_code VARCHAR(32),
    visit_count INTEGER NOT NULL,
    display_code VARCHAR(32),
    display_seq INTEGER,
    course_access_token VARCHAR(64),
    metadata_json TEXT
);

-- backend/src/main/java/com/example/app/guest/model/GuestEntitlementUsage.java
CREATE TABLE IF NOT EXISTS guest_entitlement_usages (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    entitlement_id BIGINT NOT NULL,
    session_booking_id BIGINT,
    units_used INTEGER NOT NULL,
    reason VARCHAR(64) NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE NOT NULL,
    scan_source VARCHAR(16),
    scanned_by_user_id BIGINT,
    units_before INTEGER,
    units_after INTEGER
);

-- backend/src/main/java/com/example/app/guest/model/GuestNotification.java
CREATE TABLE IF NOT EXISTS guest_notifications (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    guest_user_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    client_id BIGINT,
    notification_type VARCHAR(40) NOT NULL,
    title VARCHAR(200) NOT NULL,
    body TEXT NOT NULL,
    payload_json TEXT,
    read_at TIMESTAMP WITH TIME ZONE
);

-- backend/src/main/java/com/example/app/guest/model/GuestOrder.java
CREATE TABLE IF NOT EXISTS guest_orders (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    guest_user_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    payment_method_type VARCHAR(32) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    subtotal_gross NUMERIC(19, 4) NOT NULL,
    tax_amount NUMERIC(19, 4) NOT NULL,
    total_gross NUMERIC(19, 4) NOT NULL,
    reference_code VARCHAR(120) NOT NULL,
    stripe_checkout_session_id VARCHAR(255),
    stripe_payment_intent_id VARCHAR(255),
    stripe_customer_id VARCHAR(255),
    stripe_connected_account_id VARCHAR(255),
    stripe_connect_mode VARCHAR(32),
    metadata_json TEXT,
    paypal_order_id VARCHAR(255),
    paypal_capture_id VARCHAR(255),
    bill_id BIGINT,
    invoice_locale VARCHAR(8),
    paid_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE
);

-- backend/src/main/java/com/example/app/guest/model/GuestOrderItem.java
CREATE TABLE IF NOT EXISTS guest_order_items (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    session_type_id BIGINT,
    quantity INTEGER NOT NULL,
    unit_price_gross NUMERIC(19, 4) NOT NULL,
    line_total_gross NUMERIC(19, 4) NOT NULL,
    metadata_json TEXT
);

-- backend/src/main/java/com/example/app/guest/model/GuestProduct.java
CREATE TABLE IF NOT EXISTS guest_products (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    session_type_id BIGINT,
    transaction_service_id BIGINT,
    course_id BIGINT,
    name VARCHAR(160) NOT NULL,
    description TEXT,
    promo_text VARCHAR(120),
    product_type VARCHAR(32) NOT NULL,
    price_gross NUMERIC(19, 4) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    active BOOLEAN NOT NULL,
    guest_visible BOOLEAN NOT NULL,
    bookable BOOLEAN NOT NULL,
    usage_limit INTEGER,
    validity_days INTEGER,
    auto_renews BOOLEAN NOT NULL,
    sort_order INTEGER NOT NULL,
    booking_rules_json TEXT,
    entitlement_rules_json TEXT
);

-- backend/src/main/java/com/example/app/guest/model/GuestTenantLink.java
CREATE TABLE IF NOT EXISTS guest_tenant_links (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    guest_user_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    joined_via VARCHAR(32) NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_used_at TIMESTAMP WITH TIME ZONE,
    guest_inbox_last_read_at TIMESTAMP WITH TIME ZONE,
    staff_inbox_last_read_at TIMESTAMP WITH TIME ZONE
);

-- backend/src/main/java/com/example/app/guest/model/GuestUser.java
CREATE TABLE IF NOT EXISTS guest_users (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255),
    first_name VARCHAR(120) NOT NULL,
    last_name VARCHAR(120) NOT NULL,
    phone VARCHAR(60),
    language VARCHAR(8) NOT NULL,
    active BOOLEAN NOT NULL,
    email_verified BOOLEAN NOT NULL,
    notify_messages_enabled BOOLEAN NOT NULL,
    notify_reminders_enabled BOOLEAN NOT NULL,
    notify_reminder_minutes INTEGER NOT NULL DEFAULT 60,
    google_subject VARCHAR(255),
    apple_subject VARCHAR(255),
    stripe_customer_id VARCHAR(255),
    profile_picture_s3_key VARCHAR(512),
    profile_picture_content_type VARCHAR(120),
    last_login_at TIMESTAMP WITH TIME ZONE
);

-- backend/src/main/java/com/example/app/guest/model/TenantInvite.java
CREATE TABLE IF NOT EXISTS tenant_invites (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    code VARCHAR(120) NOT NULL,
    label VARCHAR(120),
    active BOOLEAN NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    max_uses INTEGER,
    used_count INTEGER NOT NULL,
    created_by_user_id BIGINT
);

-- backend/src/main/java/com/example/app/inbox/ClientMessage.java
CREATE TABLE IF NOT EXISTS client_messages (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    sender_user_id BIGINT,
    guest_user_id BIGINT,
    channel VARCHAR(20) NOT NULL,
    direction VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    recipient VARCHAR(255) NOT NULL,
    subject VARCHAR(255),
    body TEXT NOT NULL,
    external_message_id VARCHAR(255),
    error_message VARCHAR(2000),
    conversation_key VARCHAR(80),
    conversation_closed BOOLEAN NOT NULL,
    conversation_starred BOOLEAN NOT NULL,
    internal_note BOOLEAN NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE
);

-- backend/src/main/java/com/example/app/inbox/ClientMessageAttachment.java
CREATE TABLE IF NOT EXISTS client_message_attachments (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    message_id BIGINT NOT NULL,
    client_file_id BIGINT NOT NULL
);

-- backend/src/main/java/com/example/app/inbox/ScheduledMessage.java
CREATE TABLE IF NOT EXISTS scheduled_messages (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    sender_user_id BIGINT,
    channel VARCHAR(20) NOT NULL,
    subject VARCHAR(255),
    body TEXT NOT NULL,
    next_run_at TIMESTAMP WITH TIME ZONE NOT NULL,
    recurrence VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    last_run_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(2000)
);

-- backend/src/main/java/com/example/app/mfa/RecoveryCode.java
CREATE TABLE IF NOT EXISTS recovery_codes (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id BIGINT NOT NULL,
    code_hash VARCHAR(255) NOT NULL,
    code_hint VARCHAR(64) NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE
);

-- backend/src/main/java/com/example/app/mfa/WebAuthnCredential.java
CREATE TABLE IF NOT EXISTS webauthn_credentials (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id BIGINT NOT NULL,
    credential_id VARCHAR(512) NOT NULL,
    public_key_cose TEXT NOT NULL,
    signature_count BIGINT NOT NULL,
    label VARCHAR(255),
    transports_json VARCHAR(255),
    discoverable BOOLEAN NOT NULL,
    backup_eligible BOOLEAN,
    backup_state BOOLEAN,
    last_used_at TIMESTAMP WITH TIME ZONE
);

-- backend/src/main/java/com/example/app/securitycenter/SecurityActivityEvent.java
CREATE TABLE IF NOT EXISTS security_activity_events (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    title VARCHAR(160) NOT NULL,
    detail VARCHAR(500),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    risk_level VARCHAR(64),
    ip_address VARCHAR(128),
    user_agent VARCHAR(500)
);

-- backend/src/main/java/com/example/app/securitycenter/SecurityAlertPreference.java
CREATE TABLE IF NOT EXISTS security_alert_preferences (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id BIGINT NOT NULL,
    factor_change_alerts_enabled BOOLEAN NOT NULL,
    suspicious_sign_in_alerts_enabled BOOLEAN NOT NULL
);

-- backend/src/main/java/com/example/app/securitycenter/UserSecuritySession.java
CREATE TABLE IF NOT EXISTS user_security_sessions (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id BIGINT NOT NULL,
    session_key VARCHAR(64) NOT NULL,
    label VARCHAR(160),
    user_agent VARCHAR(500),
    ip_address VARCHAR(128),
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    revoke_reason VARCHAR(128)
);

-- backend/src/main/java/com/example/app/session/BookableSlot.java
CREATE TABLE IF NOT EXISTS bookable_slot (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    day_of_week VARCHAR(255) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    consultant_id BIGINT NOT NULL,
    indefinite BOOLEAN NOT NULL,
    start_date DATE,
    end_date DATE
);

-- backend/src/main/java/com/example/app/session/CalendarTodo.java
CREATE TABLE IF NOT EXISTS calendar_todos (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    task VARCHAR(200) NOT NULL,
    notes VARCHAR(1000)
);

-- backend/src/main/java/com/example/app/session/PersonalCalendarBlock.java
CREATE TABLE IF NOT EXISTS personal_calendar_block (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    task VARCHAR(200) NOT NULL,
    notes VARCHAR(1000)
);

-- backend/src/main/java/com/example/app/session/SessionBooking.java
CREATE TABLE IF NOT EXISTS session_booking (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    client_id BIGINT,
    booking_group_key VARCHAR(64),
    consultant_id BIGINT,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    space_id BIGINT,
    type_id BIGINT,
    notes VARCHAR(1000),
    meeting_link VARCHAR(500),
    meeting_provider VARCHAR(20),
    billed_at DATE,
    reminder_sent_at TIMESTAMP,
    notification_before_sent_at TIMESTAMP,
    notification_after_sent_at TIMESTAMP,
    booking_status VARCHAR(32),
    source_channel VARCHAR(32),
    source_order_id VARCHAR(64),
    guest_user_id VARCHAR(64),
    client_group_id BIGINT,
    session_group_email_override VARCHAR(512),
    session_group_billing_company_id BIGINT,
    payee_type VARCHAR(16),
    payee_company_id BIGINT,
    payee_custom_data BOOLEAN NOT NULL,
    payee_person_first_name VARCHAR(255),
    payee_person_last_name VARCHAR(255),
    payee_person_email VARCHAR(512),
    payee_company_name VARCHAR(255),
    payee_company_address VARCHAR(512),
    payee_company_city VARCHAR(255),
    payee_company_postal_code VARCHAR(64),
    payee_company_vat_id VARCHAR(64),
    payee_company_email VARCHAR(512)
);

-- ============================================================================
-- Squashed from V2__guest_booking_push_reminders.sql
-- ============================================================================

CREATE TABLE IF NOT EXISTS booking_push_reminders (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    booking_id BIGINT NOT NULL,
    guest_user_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    due_at TIMESTAMP NOT NULL,
    booking_start_at TIMESTAMP NOT NULL,
    reminder_minutes INTEGER NOT NULL,
    status VARCHAR(16) NOT NULL,
    sent_at TIMESTAMP,
    failed_at TIMESTAMP,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(1000)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_booking_push_reminders_booking_guest
    ON booking_push_reminders (booking_id, guest_user_id);
CREATE INDEX IF NOT EXISTS idx_booking_push_reminders_due
    ON booking_push_reminders (status, due_at, id);
CREATE INDEX IF NOT EXISTS idx_booking_push_reminders_guest_status
    ON booking_push_reminders (guest_user_id, status, due_at);
CREATE INDEX IF NOT EXISTS idx_booking_push_reminders_booking
    ON booking_push_reminders (booking_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_booking_push_reminders_booking') THEN
        ALTER TABLE booking_push_reminders ADD CONSTRAINT fk_booking_push_reminders_booking
            FOREIGN KEY (booking_id) REFERENCES session_booking(id) ON DELETE CASCADE NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_booking_push_reminders_guest_user') THEN
        ALTER TABLE booking_push_reminders ADD CONSTRAINT fk_booking_push_reminders_guest_user
            FOREIGN KEY (guest_user_id) REFERENCES guest_users(id) ON DELETE CASCADE NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_booking_push_reminders_company') THEN
        ALTER TABLE booking_push_reminders ADD CONSTRAINT fk_booking_push_reminders_company
            FOREIGN KEY (company_id) REFERENCES company(id) ON DELETE CASCADE NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_booking_push_reminders_client') THEN
        ALTER TABLE booking_push_reminders ADD CONSTRAINT fk_booking_push_reminders_client
            FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_guest_notify_reminder_minutes') THEN
        ALTER TABLE guest_users ADD CONSTRAINT chk_guest_notify_reminder_minutes
            CHECK (notify_reminder_minutes IN (5, 15, 30, 60, 180, 1440)) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_booking_push_reminder_minutes') THEN
        ALTER TABLE booking_push_reminders ADD CONSTRAINT chk_booking_push_reminder_minutes
            CHECK (reminder_minutes IN (5, 15, 30, 60, 180, 1440)) NOT VALID;
    END IF;
END $$;

-- backend/src/main/java/com/example/app/session/SessionType.java
CREATE TABLE IF NOT EXISTS session_type (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    duration_minutes INTEGER,
    break_minutes INTEGER,
    max_participants_per_session INTEGER,
    widget_group_booking_enabled BOOLEAN NOT NULL,
    guest_booking_enabled BOOLEAN NOT NULL,
    group_booking_enabled BOOLEAN NOT NULL,
    guest_limit_user_emails TEXT,
    price_calculation_mode VARCHAR(24) NOT NULL,
    guest_booking_description TEXT,
    guest_sort_order INTEGER NOT NULL,
    active BOOLEAN NOT NULL
);

-- backend/src/main/java/com/example/app/session/Space.java
CREATE TABLE IF NOT EXISTS space (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255)
);

-- backend/src/main/java/com/example/app/session/TypeTransactionService.java
CREATE TABLE IF NOT EXISTS type_transaction_services (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    session_type_id BIGINT NOT NULL,
    transaction_service_id BIGINT NOT NULL,
    price NUMERIC(19, 4)
);

-- backend/src/main/java/com/example/app/settings/AppSetting.java
CREATE TABLE IF NOT EXISTS app_settings (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    key VARCHAR(255) NOT NULL,
    value TEXT NOT NULL
);

-- backend/src/main/java/com/example/app/stripe/StripeWebhookEvent.java
CREATE TABLE IF NOT EXISTS stripe_webhook_events (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    event_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    processing_status VARCHAR(255) NOT NULL,
    payload TEXT,
    error_message TEXT
);

-- backend/src/main/java/com/example/app/user/EmployeeAccessRole.java
CREATE TABLE IF NOT EXISTS employee_access_roles (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    permissions_json TEXT
);

-- backend/src/main/java/com/example/app/user/User.java
CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    consultant BOOLEAN NOT NULL,
    vat_id VARCHAR(64),
    phone VARCHAR(64),
    whatsapp_sender_number VARCHAR(64),
    whatsapp_phone_number_id VARCHAR(128),
    working_hours_json TEXT,
    webauthn_user_handle VARCHAR(255),
    factor_change_alerts_enabled BOOLEAN,
    suspicious_sign_in_alerts_enabled BOOLEAN,
    permissions_json TEXT,
    employee_access_role_id BIGINT,
    avatar_s3_key VARCHAR(512),
    avatar_content_type VARCHAR(120)
);

-- backend/src/main/java/com/example/app/widget/WidgetBookingIdempotencyRecord.java
CREATE TABLE IF NOT EXISTS widget_booking_idempotency (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    endpoint VARCHAR(80) NOT NULL,
    payload_hash VARCHAR(128) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'IN_PROGRESS',
    response_json TEXT,
    completed_at TIMESTAMP WITH TIME ZONE,
    failed_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(1000)
);


-- backend/src/main/java/com/example/app/widget/manage/PublicBookingManageToken.java
CREATE TABLE IF NOT EXISTS public_booking_manage_tokens (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    booking_id BIGINT NOT NULL,
    token_hash VARCHAR(128) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_used_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE
);

-- backend/src/main/java/com/example/app/zoom/ZoomOAuthToken.java
CREATE TABLE IF NOT EXISTS zoom_oauth_tokens (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    access_token VARCHAR(2000) NOT NULL,
    refresh_token VARCHAR(2000),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Explicit many-to-many join tables used by the JPA model.
CREATE TABLE IF NOT EXISTS user_spaces (
    user_id BIGINT NOT NULL,
    space_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, space_id)
);

CREATE TABLE IF NOT EXISTS user_types (
    user_id BIGINT NOT NULL,
    type_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, type_id)
);

CREATE TABLE IF NOT EXISTS client_group_members (
    group_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    PRIMARY KEY (group_id, client_id)
);


-- ============================================================================
-- Squashed from V5__post_baseline_production_readiness_indexes_and_constraints.sql
-- ============================================================================

-- Post-baseline replay of production-readiness indexes/constraints for clean Flyway-created schemas.
-- Flyway is enabled only in staging/production profiles; local dev can still use Hibernate ddl-auto=update.
-- This repeats V1 defensively because V1 can run before V3 on a clean database and skip table-specific indexes.

DO $$
BEGIN
    IF to_regclass('public.session_booking') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_session_booking_company_time_active
                 ON session_booking (company_id, start_time, end_time)
                 WHERE upper(coalesce(booking_status, ''RESERVED'')) NOT IN (''CANCELLED'', ''NO_SHOW'')';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_session_booking_company_consultant_time_active
                 ON session_booking (company_id, consultant_id, start_time, end_time)
                 WHERE consultant_id IS NOT NULL
                   AND upper(coalesce(booking_status, ''RESERVED'')) NOT IN (''CANCELLED'', ''NO_SHOW'')';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_session_booking_company_client_time_active
                 ON session_booking (company_id, client_id, start_time, end_time)
                 WHERE client_id IS NOT NULL
                   AND upper(coalesce(booking_status, ''RESERVED'')) NOT IN (''CANCELLED'', ''NO_SHOW'')';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_session_booking_company_space_time_active
                 ON session_booking (company_id, space_id, start_time, end_time)
                 WHERE space_id IS NOT NULL
                   AND (meeting_link IS NULL OR meeting_link = '''')
                   AND upper(coalesce(booking_status, ''RESERVED'')) NOT IN (''CANCELLED'', ''NO_SHOW'')';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_session_booking_company_group_key
                 ON session_booking (company_id, booking_group_key, id)
                 WHERE booking_group_key IS NOT NULL';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_session_booking_company_source_order
                 ON session_booking (company_id, source_order_id)
                 WHERE source_order_id IS NOT NULL';

        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_session_booking_time_order') THEN
            EXECUTE 'ALTER TABLE session_booking
                     ADD CONSTRAINT chk_session_booking_time_order CHECK (end_time > start_time) NOT VALID';
        END IF;
    END IF;

    IF to_regclass('public.bookable_slot') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_bookable_slot_company_day_consultant_dates
                 ON bookable_slot (company_id, day_of_week, consultant_id, start_date, end_date, start_time, end_time)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_bookable_slot_consultant_company_day_time
                 ON bookable_slot (consultant_id, company_id, day_of_week, start_time, end_time)';

        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_bookable_slot_time_order') THEN
            EXECUTE 'ALTER TABLE bookable_slot
                     ADD CONSTRAINT chk_bookable_slot_time_order CHECK (end_time > start_time) NOT VALID';
        END IF;
    END IF;

    IF to_regclass('public.clients') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_clients_company_normalized_email
                 ON clients (company_id, lower(trim(email)))
                 WHERE email IS NOT NULL AND trim(email) <> ''''';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_clients_company_trimmed_phone
                 ON clients (company_id, trim(phone))
                 WHERE phone IS NOT NULL AND trim(phone) <> ''''';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_clients_company_active_assigned
                 ON clients (company_id, active, assigned_to_id, id)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_clients_company_created_at
                 ON clients (company_id, created_at, id)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_clients_company_assigned_created_at
                 ON clients (company_id, assigned_to_id, created_at, id)
                 WHERE assigned_to_id IS NOT NULL';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_clients_company_billing_company
                 ON clients (company_id, billing_company_id) WHERE billing_company_id IS NOT NULL';
    END IF;

    IF to_regclass('public.users') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_users_company_active_role
                 ON users (company_id, active, role, id)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_users_company_active_consultant
                 ON users (company_id, active, consultant, id)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_users_company_lower_email
                 ON users (company_id, lower(email))';
    END IF;
    IF to_regclass('public.idx_users_company_employee_access_role_active') IS NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_users_company_employee_access_role_active
                 ON users (company_id, employee_access_role_id, active)';
    END IF;
    IF to_regclass('public.idx_employee_access_roles_company_archived') IS NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_employee_access_roles_company_archived
                 ON employee_access_roles (company_id, archived, lower(name))';
    END IF;
    IF to_regclass('public.ux_employee_access_roles_company_lower_name_active') IS NULL THEN
        EXECUTE 'CREATE UNIQUE INDEX IF NOT EXISTS ux_employee_access_roles_company_lower_name_active
                 ON employee_access_roles (company_id, lower(name)) WHERE archived = false';
    END IF;

    IF to_regclass('public.app_settings') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_app_settings_company_key
                 ON app_settings (company_id, key)';
    END IF;

    IF to_regclass('public.payment_methods') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_payment_method_company_type
                 ON payment_methods (company_id, payment_type, guest_enabled, widget_enabled)';
    END IF;

    IF to_regclass('public.open_bills') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_open_bills_company_created
                 ON open_bills (company_id, created_at DESC, id DESC)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_open_bills_company_reference
                 ON open_bills (company_id, reference)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_open_bills_company_client_consultant
                 ON open_bills (company_id, client_id, consultant_id, id)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_open_bills_company_group_key
                 ON open_bills (company_id, booking_group_key) WHERE booking_group_key IS NOT NULL';
    END IF;

    IF to_regclass('public.bills') IS NOT NULL THEN
        EXECUTE 'CREATE UNIQUE INDEX IF NOT EXISTS ux_bills_company_bill_number
                 ON bills (company_id, bill_number)';
        EXECUTE 'CREATE UNIQUE INDEX IF NOT EXISTS ux_bills_company_order_id
                 ON bills (company_id, order_id)
                 WHERE order_id IS NOT NULL';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_bill_company_issue_date
                 ON bills (company_id, issue_date DESC, id DESC)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_bill_company_type_issue_date
                 ON bills (company_id, bill_type, issue_date DESC, id DESC)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_bill_company_source_session_type
                 ON bills (company_id, source_session_id_snapshot, bill_type)';
    END IF;

    IF to_regclass('public.guest_orders') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_guest_orders_company_guest_status_created
                 ON guest_orders (company_id, guest_user_id, status, created_at DESC, id DESC)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_guest_orders_company_client_status_created
                 ON guest_orders (company_id, client_id, status, created_at DESC, id DESC)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_guest_orders_stripe_checkout_session
                 ON guest_orders (stripe_checkout_session_id)
                 WHERE stripe_checkout_session_id IS NOT NULL';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_guest_orders_paypal_order
                 ON guest_orders (paypal_order_id)
                 WHERE paypal_order_id IS NOT NULL';

        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_guest_orders_amounts_non_negative') THEN
            EXECUTE 'ALTER TABLE guest_orders
                     ADD CONSTRAINT chk_guest_orders_amounts_non_negative
                     CHECK (subtotal_gross >= 0 AND tax_amount >= 0 AND total_gross >= 0) NOT VALID';
        END IF;
    END IF;

    IF to_regclass('public.guest_entitlement') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_guest_entitlement_company_client_status_valid
                 ON guest_entitlement (company_id, client_id, status, valid_until, id)';
    ELSIF to_regclass('public.guest_entitlements') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_guest_entitlements_company_client_status_valid
                 ON guest_entitlements (company_id, client_id, status, valid_until, id)';
    END IF;

    IF to_regclass('public.guest_products') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_guest_products_company_active_type_sort
                 ON guest_products (company_id, active, product_type, sort_order, id)';
    END IF;

    IF to_regclass('public.guest_tenant_links') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_guest_tenant_links_company_status_client
                 ON guest_tenant_links (company_id, status, client_id)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_guest_tenant_links_guest_status
                 ON guest_tenant_links (guest_user_id, status, last_used_at DESC)';
    END IF;

    IF to_regclass('public.widget_booking_idempotency') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_widget_booking_idempotency_lookup
                 ON widget_booking_idempotency (company_id, idempotency_key, endpoint)';
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'widget_booking_idempotency' AND column_name = 'status'
        ) THEN
            ALTER TABLE widget_booking_idempotency ADD COLUMN status VARCHAR(24) NOT NULL DEFAULT 'IN_PROGRESS';
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'widget_booking_idempotency' AND column_name = 'completed_at'
        ) THEN
            ALTER TABLE widget_booking_idempotency ADD COLUMN completed_at TIMESTAMP WITH TIME ZONE;
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'widget_booking_idempotency' AND column_name = 'failed_at'
        ) THEN
            ALTER TABLE widget_booking_idempotency ADD COLUMN failed_at TIMESTAMP WITH TIME ZONE;
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'widget_booking_idempotency' AND column_name = 'last_error'
        ) THEN
            ALTER TABLE widget_booking_idempotency ADD COLUMN last_error VARCHAR(1000);
        END IF;
        ALTER TABLE widget_booking_idempotency ALTER COLUMN response_json DROP NOT NULL;
    END IF;

    IF to_regclass('public.public_booking_manage_tokens') IS NOT NULL THEN
        EXECUTE 'CREATE UNIQUE INDEX IF NOT EXISTS ux_public_booking_manage_tokens_hash
                 ON public_booking_manage_tokens (token_hash)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_public_booking_manage_tokens_booking
                 ON public_booking_manage_tokens (booking_id)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_public_booking_manage_tokens_company
                 ON public_booking_manage_tokens (company_id)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_public_booking_manage_tokens_active
                 ON public_booking_manage_tokens (token_hash, revoked_at, expires_at)';
    END IF;

    IF to_regclass('public.guest_device_tokens') IS NOT NULL THEN
        EXECUTE 'CREATE UNIQUE INDEX IF NOT EXISTS ux_guest_device_tokens_push_token
                 ON guest_device_tokens (push_token)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_guest_device_tokens_guest_updated
                 ON guest_device_tokens (guest_user_id, updated_at DESC)';
    END IF;
END $$;

DO $$
BEGIN
    -- Create important uniqueness guarantees only when existing data is already clean.
    -- If duplicates exist, this migration logs a NOTICE and continues so deployment does not fail unexpectedly.
    IF to_regclass('public.company') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'ux_companies_lower_tenant_code')
       AND NOT EXISTS (
           SELECT 1 FROM (
               SELECT lower(tenant_code) AS tenant_code_key
               FROM company
               WHERE tenant_code IS NOT NULL AND trim(tenant_code) <> ''
               GROUP BY lower(tenant_code)
               HAVING count(*) > 1
           ) duplicates
       ) THEN
        EXECUTE 'CREATE UNIQUE INDEX ux_companies_lower_tenant_code
                 ON company (lower(tenant_code))
                 WHERE tenant_code IS NOT NULL AND trim(tenant_code) <> ''''';
    END IF;

    IF to_regclass('public.users') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'ux_users_company_lower_email')
       AND NOT EXISTS (
           SELECT 1 FROM (
               SELECT company_id, lower(email) AS email_key
               FROM users
               WHERE email IS NOT NULL AND trim(email) <> ''
               GROUP BY company_id, lower(email)
               HAVING count(*) > 1
           ) duplicates
       ) THEN
        EXECUTE 'CREATE UNIQUE INDEX ux_users_company_lower_email
                 ON users (company_id, lower(email))
                 WHERE email IS NOT NULL AND trim(email) <> ''''';
    END IF;

    IF to_regclass('public.app_settings') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'ux_app_settings_company_key')
       AND NOT EXISTS (
           SELECT 1 FROM (
               SELECT company_id, key
               FROM app_settings
               GROUP BY company_id, key
               HAVING count(*) > 1
           ) duplicates
       ) THEN
        EXECUTE 'CREATE UNIQUE INDEX ux_app_settings_company_key ON app_settings (company_id, key)';
    END IF;

    IF to_regclass('public.guest_tenant_links') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'ux_guest_tenant_links_guest_company')
       AND NOT EXISTS (
           SELECT 1 FROM (
               SELECT guest_user_id, company_id
               FROM guest_tenant_links
               GROUP BY guest_user_id, company_id
               HAVING count(*) > 1
           ) duplicates
       ) THEN
        EXECUTE 'CREATE UNIQUE INDEX ux_guest_tenant_links_guest_company ON guest_tenant_links (guest_user_id, company_id)';
    END IF;

    IF to_regclass('public.widget_booking_idempotency') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'ux_widget_booking_idempotency_company_key_endpoint')
       AND NOT EXISTS (
           SELECT 1 FROM (
               SELECT company_id, idempotency_key, endpoint
               FROM widget_booking_idempotency
               GROUP BY company_id, idempotency_key, endpoint
               HAVING count(*) > 1
           ) duplicates
       ) THEN
        EXECUTE 'CREATE UNIQUE INDEX ux_widget_booking_idempotency_company_key_endpoint
                 ON widget_booking_idempotency (company_id, idempotency_key, endpoint)';
    END IF;

    IF to_regclass('public.guest_orders') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'ux_guest_orders_reference_code')
       AND NOT EXISTS (
           SELECT 1 FROM (
               SELECT reference_code
               FROM guest_orders
               WHERE reference_code IS NOT NULL AND trim(reference_code) <> ''
               GROUP BY reference_code
               HAVING count(*) > 1
           ) duplicates
       ) THEN
        EXECUTE 'CREATE UNIQUE INDEX ux_guest_orders_reference_code
                 ON guest_orders (reference_code)
                 WHERE reference_code IS NOT NULL AND trim(reference_code) <> ''''';
    END IF;
END $$;


-- ============================================================================
-- Squashed from V2__scheduler_lock_and_booking_range_indexes.sql
-- ============================================================================

-- ShedLock table used by scheduled jobs in multi-instance staging/production deployments.
-- Keep this in Flyway so the application does not perform schema creation at runtime.
CREATE TABLE IF NOT EXISTS shedlock (
    name VARCHAR(255) NOT NULL,
    lock_until TIMESTAMP NOT NULL,
    locked_at TIMESTAMP NOT NULL,
    locked_by VARCHAR(255) NOT NULL,
    PRIMARY KEY (name)
);

-- Date-range endpoints now query bookings directly in PostgreSQL. These non-partial indexes cover
-- all statuses, including CANCELLED/NO_SHOW rows that the calendar may still need to display/filter.
DO $$
BEGIN
    IF to_regclass('public.session_booking') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_session_booking_company_time_all
                 ON session_booking (company_id, start_time, end_time, id)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_session_booking_company_consultant_time_all
                 ON session_booking (company_id, consultant_id, start_time, end_time, id)
                 WHERE consultant_id IS NOT NULL';
    END IF;

    IF to_regclass('public.open_bills') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_open_bills_company_session_booking
                 ON open_bills (company_id, session_booking_id)
                 WHERE session_booking_id IS NOT NULL';
    END IF;

    IF to_regclass('public.open_bill_items') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_open_bill_items_source_session_booking
                 ON open_bill_items (source_session_booking_id, open_bill_id)
                 WHERE source_session_booking_id IS NOT NULL';
    END IF;
END $$;


-- ============================================================================
-- Squashed from V4__pagination_and_open_bill_sync_indexes.sql
-- ============================================================================

-- Pagination and scale indexes used by production list endpoints.

DO $$
BEGIN
    IF to_regclass('public.clients') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_clients_company_name_id ON clients (company_id, last_name, first_name, id)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_clients_company_assigned_name_id ON clients (company_id, assigned_to_id, last_name, first_name, id) WHERE assigned_to_id IS NOT NULL';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_clients_company_email_lower ON clients (company_id, lower(email)) WHERE email IS NOT NULL';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_clients_company_phone ON clients (company_id, phone) WHERE phone IS NOT NULL';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_clients_company_phone_digits
                 ON clients (company_id, regexp_replace(coalesce(phone, ''''), ''[^0-9]'', '''', ''g''))
                 WHERE phone IS NOT NULL AND trim(phone) <> ''''';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_clients_company_whatsapp_phone_digits
                 ON clients (company_id, regexp_replace(coalesce(whatsapp_phone, ''''), ''[^0-9]'', '''', ''g''))
                 WHERE whatsapp_phone IS NOT NULL AND trim(whatsapp_phone) <> ''''';
    END IF;

    IF to_regclass('public.bills') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_bills_company_issue_date_id ON bills (company_id, issue_date DESC, id DESC)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_bills_company_consultant_issue_date_id
                 ON bills (company_id, consultant_id, issue_date DESC, id DESC)
                 WHERE consultant_id IS NOT NULL';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_bills_company_payment_status_id
                 ON bills (company_id, payment_status, id)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_bills_company_payment_method_status_id
                 ON bills (company_id, payment_method_id, payment_status, id)
                 WHERE payment_method_id IS NOT NULL';
    END IF;

    IF to_regclass('public.bill_item') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_bill_item_source_session_booking
                 ON bill_item (source_session_booking_id, bill_id)
                 WHERE source_session_booking_id IS NOT NULL';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_bill_item_bill_id
                 ON bill_item (bill_id)';
    END IF;

    IF to_regclass('public.bill_payments') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_bill_payments_bill_method
                 ON bill_payments (bill_id, payment_method_id)';
    END IF;

    IF to_regclass('public.open_bills') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_open_bills_company_id_desc ON open_bills (company_id, id DESC)';
    END IF;

    IF to_regclass('public.client_messages') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_client_messages_company_created_id ON client_messages (company_id, created_at DESC, id DESC)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_client_messages_company_client_created_id ON client_messages (company_id, client_id, created_at DESC, id DESC)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_client_messages_company_client_conversation_created_id ON client_messages (company_id, client_id, conversation_key, created_at DESC, id DESC)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_client_messages_company_channel_created_id ON client_messages (company_id, channel, created_at DESC, id DESC)';
    END IF;

    IF to_regclass('public.guest_orders') IS NOT NULL THEN
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_guest_orders_guest_company_created_id ON guest_orders (guest_user_id, company_id, created_at DESC, id DESC)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_guest_orders_guest_company_status_created_id ON guest_orders (guest_user_id, company_id, status, created_at DESC, id DESC)';
        EXECUTE 'CREATE INDEX IF NOT EXISTS idx_guest_orders_client_company_status_created_id ON guest_orders (client_id, company_id, status, created_at DESC, id DESC)';
    END IF;
END $$;


-- ============================================================================
-- Squashed from V6__open_bill_dirty_queue_and_schema_validation.sql
-- ============================================================================

-- Production scale hardening:
-- 1) dirty/due open-bill sync queue so scheduled workers process only affected sessions/groups;
-- 2) DB-limited guest/mobile list indexes;
-- 3) fail-fast validation of critical relational constraints after the baseline schema.

DO $$
DECLARE
    required_table text;
    required_tables text[] := ARRAY[
        'company', 'users', 'clients', 'session_booking', 'session_type', 'space',
        'transaction_service', 'payment_methods', 'open_bills', 'open_bill_items',
        'bills', 'bill_item', 'guest_users', 'guest_orders', 'guest_order_items',
        'guest_products', 'guest_entitlements', 'guest_entitlement_usages', 'guest_notifications'
    ];
BEGIN
    FOREACH required_table IN ARRAY required_tables LOOP
        IF to_regclass('public.' || required_table) IS NULL THEN
            RAISE EXCEPTION 'Required table %.% is missing; Flyway baseline is incomplete', 'public', required_table;
        END IF;
    END LOOP;
END $$;

CREATE TABLE IF NOT EXISTS open_bill_sync_queue (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL,
    session_booking_id BIGINT,
    booking_group_key VARCHAR(64),
    due_at TIMESTAMP WITH TIME ZONE NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(1000),
    CONSTRAINT chk_open_bill_sync_queue_target CHECK (
        session_booking_id IS NOT NULL OR (booking_group_key IS NOT NULL AND trim(booking_group_key) <> '')
    ),
    CONSTRAINT fk_open_bill_sync_queue_company FOREIGN KEY (company_id) REFERENCES company(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_open_bill_sync_queue_session
    ON open_bill_sync_queue (company_id, session_booking_id)
    WHERE session_booking_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_open_bill_sync_queue_group
    ON open_bill_sync_queue (company_id, booking_group_key)
    WHERE booking_group_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_open_bill_sync_queue_due
    ON open_bill_sync_queue (due_at ASC, id ASC);

CREATE INDEX IF NOT EXISTS idx_guest_notifications_user_company_created_id
    ON guest_notifications (guest_user_id, company_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_session_booking_company_client_start_id
    ON session_booking (company_id, client_id, start_time DESC, id DESC)
    WHERE client_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_guest_entitlements_client_company_status_created_id
    ON guest_entitlements (client_id, company_id, status, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_guest_entitlements_source_order_created_id
    ON guest_entitlements (source_order_id, created_at ASC, id ASC)
    WHERE source_order_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_guest_entitlement_usages_entitlement_used_id
    ON guest_entitlement_usages (entitlement_id, used_at DESC, id DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_companies_lower_tenant_code
    ON company (lower(tenant_code))
    WHERE tenant_code IS NOT NULL AND trim(tenant_code) <> '';
CREATE UNIQUE INDEX IF NOT EXISTS ux_app_settings_company_key
    ON app_settings (company_id, key);
CREATE UNIQUE INDEX IF NOT EXISTS ux_guest_orders_reference_code
    ON guest_orders (reference_code)
    WHERE reference_code IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_guest_entitlements_entitlement_code
    ON guest_entitlements (entitlement_code)
    WHERE entitlement_code IS NOT NULL AND trim(entitlement_code) <> '';
CREATE UNIQUE INDEX IF NOT EXISTS ux_guest_entitlements_course_access_token
    ON guest_entitlements (course_access_token)
    WHERE course_access_token IS NOT NULL AND trim(course_access_token) <> '';
CREATE UNIQUE INDEX IF NOT EXISTS ux_guest_entitlements_gift_card_company_seq
    ON guest_entitlements (company_id, display_seq)
    WHERE entitlement_type = 'GIFT_CARD' AND display_seq IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_guest_entitlements_gift_card_company_display_code
    ON guest_entitlements (company_id, lower(display_code))
    WHERE entitlement_type = 'GIFT_CARD' AND display_code IS NOT NULL AND trim(display_code) <> '';

DO $$
BEGIN
    -- Check constraints: add when missing, then validate. Validation intentionally fails deployment on dirty data.
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_session_booking_time_order') THEN
        ALTER TABLE session_booking ADD CONSTRAINT chk_session_booking_time_order CHECK (end_time > start_time) NOT VALID;
    END IF;
    ALTER TABLE session_booking VALIDATE CONSTRAINT chk_session_booking_time_order;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_bookable_slot_time_order')
       AND to_regclass('public.bookable_slot') IS NOT NULL THEN
        ALTER TABLE bookable_slot ADD CONSTRAINT chk_bookable_slot_time_order CHECK (end_time > start_time) NOT VALID;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_bookable_slot_time_order') THEN
        ALTER TABLE bookable_slot VALIDATE CONSTRAINT chk_bookable_slot_time_order;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_guest_orders_amounts_non_negative') THEN
        ALTER TABLE guest_orders ADD CONSTRAINT chk_guest_orders_amounts_non_negative
            CHECK (subtotal_gross >= 0 AND tax_amount >= 0 AND total_gross >= 0) NOT VALID;
    END IF;
    ALTER TABLE guest_orders VALIDATE CONSTRAINT chk_guest_orders_amounts_non_negative;
END $$;

DO $$
BEGIN
    -- Core ownership and booking relations.
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_employee_access_roles_company') THEN
        ALTER TABLE employee_access_roles ADD CONSTRAINT fk_employee_access_roles_company FOREIGN KEY (company_id) REFERENCES company(id) NOT VALID;
    END IF;
    ALTER TABLE employee_access_roles VALIDATE CONSTRAINT fk_employee_access_roles_company;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_company') THEN
        ALTER TABLE users ADD CONSTRAINT fk_users_company FOREIGN KEY (company_id) REFERENCES company(id) NOT VALID;
    END IF;
    ALTER TABLE users VALIDATE CONSTRAINT fk_users_company;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_employee_access_role') THEN
        ALTER TABLE users ADD CONSTRAINT fk_users_employee_access_role FOREIGN KEY (employee_access_role_id) REFERENCES employee_access_roles(id) NOT VALID;
    END IF;
    ALTER TABLE users VALIDATE CONSTRAINT fk_users_employee_access_role;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_clients_company') THEN
        ALTER TABLE clients ADD CONSTRAINT fk_clients_company FOREIGN KEY (company_id) REFERENCES company(id) NOT VALID;
    END IF;
    ALTER TABLE clients VALIDATE CONSTRAINT fk_clients_company;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_clients_assigned_to') THEN
        ALTER TABLE clients ADD CONSTRAINT fk_clients_assigned_to FOREIGN KEY (assigned_to_id) REFERENCES users(id) NOT VALID;
    END IF;
    ALTER TABLE clients VALIDATE CONSTRAINT fk_clients_assigned_to;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_session_booking_company') THEN
        ALTER TABLE session_booking ADD CONSTRAINT fk_session_booking_company FOREIGN KEY (company_id) REFERENCES company(id) NOT VALID;
    END IF;
    ALTER TABLE session_booking VALIDATE CONSTRAINT fk_session_booking_company;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_session_booking_client') THEN
        ALTER TABLE session_booking ADD CONSTRAINT fk_session_booking_client FOREIGN KEY (client_id) REFERENCES clients(id) NOT VALID;
    END IF;
    ALTER TABLE session_booking VALIDATE CONSTRAINT fk_session_booking_client;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_session_booking_consultant') THEN
        ALTER TABLE session_booking ADD CONSTRAINT fk_session_booking_consultant FOREIGN KEY (consultant_id) REFERENCES users(id) NOT VALID;
    END IF;
    ALTER TABLE session_booking VALIDATE CONSTRAINT fk_session_booking_consultant;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_session_booking_type') THEN
        ALTER TABLE session_booking ADD CONSTRAINT fk_session_booking_type FOREIGN KEY (type_id) REFERENCES session_type(id) NOT VALID;
    END IF;
    ALTER TABLE session_booking VALIDATE CONSTRAINT fk_session_booking_type;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_session_booking_space') THEN
        ALTER TABLE session_booking ADD CONSTRAINT fk_session_booking_space FOREIGN KEY (space_id) REFERENCES space(id) NOT VALID;
    END IF;
    ALTER TABLE session_booking VALIDATE CONSTRAINT fk_session_booking_space;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_session_type_company') THEN
        ALTER TABLE session_type ADD CONSTRAINT fk_session_type_company FOREIGN KEY (company_id) REFERENCES company(id) NOT VALID;
    END IF;
    ALTER TABLE session_type VALIDATE CONSTRAINT fk_session_type_company;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_space_company') THEN
        ALTER TABLE space ADD CONSTRAINT fk_space_company FOREIGN KEY (company_id) REFERENCES company(id) NOT VALID;
    END IF;
    ALTER TABLE space VALIDATE CONSTRAINT fk_space_company;
END $$;

DO $$
BEGIN
    -- Billing and open-bill relations.
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_payment_methods_company') THEN
        ALTER TABLE payment_methods ADD CONSTRAINT fk_payment_methods_company FOREIGN KEY (company_id) REFERENCES company(id) NOT VALID;
    END IF;
    ALTER TABLE payment_methods VALIDATE CONSTRAINT fk_payment_methods_company;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_transaction_service_company') THEN
        ALTER TABLE transaction_service ADD CONSTRAINT fk_transaction_service_company FOREIGN KEY (company_id) REFERENCES company(id) NOT VALID;
    END IF;
    ALTER TABLE transaction_service VALIDATE CONSTRAINT fk_transaction_service_company;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_type_transaction_services_session_type') THEN
        ALTER TABLE type_transaction_services ADD CONSTRAINT fk_type_transaction_services_session_type FOREIGN KEY (session_type_id) REFERENCES session_type(id) NOT VALID;
    END IF;
    ALTER TABLE type_transaction_services VALIDATE CONSTRAINT fk_type_transaction_services_session_type;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_type_transaction_services_transaction_service') THEN
        ALTER TABLE type_transaction_services ADD CONSTRAINT fk_type_transaction_services_transaction_service FOREIGN KEY (transaction_service_id) REFERENCES transaction_service(id) NOT VALID;
    END IF;
    ALTER TABLE type_transaction_services VALIDATE CONSTRAINT fk_type_transaction_services_transaction_service;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_open_bills_company') THEN
        ALTER TABLE open_bills ADD CONSTRAINT fk_open_bills_company FOREIGN KEY (company_id) REFERENCES company(id) NOT VALID;
    END IF;
    ALTER TABLE open_bills VALIDATE CONSTRAINT fk_open_bills_company;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_open_bills_client') THEN
        ALTER TABLE open_bills ADD CONSTRAINT fk_open_bills_client FOREIGN KEY (client_id) REFERENCES clients(id) NOT VALID;
    END IF;
    ALTER TABLE open_bills VALIDATE CONSTRAINT fk_open_bills_client;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_open_bills_consultant') THEN
        ALTER TABLE open_bills ADD CONSTRAINT fk_open_bills_consultant FOREIGN KEY (consultant_id) REFERENCES users(id) NOT VALID;
    END IF;
    ALTER TABLE open_bills VALIDATE CONSTRAINT fk_open_bills_consultant;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_open_bills_payment_method') THEN
        ALTER TABLE open_bills ADD CONSTRAINT fk_open_bills_payment_method FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id) NOT VALID;
    END IF;
    ALTER TABLE open_bills VALIDATE CONSTRAINT fk_open_bills_payment_method;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_open_bills_session_booking') THEN
        ALTER TABLE open_bills ADD CONSTRAINT fk_open_bills_session_booking FOREIGN KEY (session_booking_id) REFERENCES session_booking(id) NOT VALID;
    END IF;
    ALTER TABLE open_bills VALIDATE CONSTRAINT fk_open_bills_session_booking;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_open_bill_items_open_bill') THEN
        ALTER TABLE open_bill_items ADD CONSTRAINT fk_open_bill_items_open_bill FOREIGN KEY (open_bill_id) REFERENCES open_bills(id) ON DELETE CASCADE NOT VALID;
    END IF;
    ALTER TABLE open_bill_items VALIDATE CONSTRAINT fk_open_bill_items_open_bill;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_open_bill_items_transaction_service') THEN
        ALTER TABLE open_bill_items ADD CONSTRAINT fk_open_bill_items_transaction_service FOREIGN KEY (transaction_service_id) REFERENCES transaction_service(id) NOT VALID;
    END IF;
    ALTER TABLE open_bill_items VALIDATE CONSTRAINT fk_open_bill_items_transaction_service;
END $$;

DO $$
BEGIN
    -- Guest app order/wallet/notification relations.
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_orders_company') THEN
        ALTER TABLE guest_orders ADD CONSTRAINT fk_guest_orders_company FOREIGN KEY (company_id) REFERENCES company(id) NOT VALID;
    END IF;
    ALTER TABLE guest_orders VALIDATE CONSTRAINT fk_guest_orders_company;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_orders_client') THEN
        ALTER TABLE guest_orders ADD CONSTRAINT fk_guest_orders_client FOREIGN KEY (client_id) REFERENCES clients(id) NOT VALID;
    END IF;
    ALTER TABLE guest_orders VALIDATE CONSTRAINT fk_guest_orders_client;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_orders_guest_user') THEN
        ALTER TABLE guest_orders ADD CONSTRAINT fk_guest_orders_guest_user FOREIGN KEY (guest_user_id) REFERENCES guest_users(id) NOT VALID;
    END IF;
    ALTER TABLE guest_orders VALIDATE CONSTRAINT fk_guest_orders_guest_user;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_orders_bill') THEN
        ALTER TABLE guest_orders ADD CONSTRAINT fk_guest_orders_bill FOREIGN KEY (bill_id) REFERENCES bills(id) NOT VALID;
    END IF;
    ALTER TABLE guest_orders VALIDATE CONSTRAINT fk_guest_orders_bill;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_order_items_order') THEN
        ALTER TABLE guest_order_items ADD CONSTRAINT fk_guest_order_items_order FOREIGN KEY (order_id) REFERENCES guest_orders(id) ON DELETE CASCADE NOT VALID;
    END IF;
    ALTER TABLE guest_order_items VALIDATE CONSTRAINT fk_guest_order_items_order;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_order_items_product') THEN
        ALTER TABLE guest_order_items ADD CONSTRAINT fk_guest_order_items_product FOREIGN KEY (product_id) REFERENCES guest_products(id) NOT VALID;
    END IF;
    ALTER TABLE guest_order_items VALIDATE CONSTRAINT fk_guest_order_items_product;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_products_company') THEN
        ALTER TABLE guest_products ADD CONSTRAINT fk_guest_products_company FOREIGN KEY (company_id) REFERENCES company(id) NOT VALID;
    END IF;
    ALTER TABLE guest_products VALIDATE CONSTRAINT fk_guest_products_company;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_products_session_type') THEN
        ALTER TABLE guest_products ADD CONSTRAINT fk_guest_products_session_type FOREIGN KEY (session_type_id) REFERENCES session_type(id) NOT VALID;
    END IF;
    ALTER TABLE guest_products VALIDATE CONSTRAINT fk_guest_products_session_type;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_products_transaction_service') THEN
        ALTER TABLE guest_products ADD CONSTRAINT fk_guest_products_transaction_service FOREIGN KEY (transaction_service_id) REFERENCES transaction_service(id) NOT VALID;
    END IF;
    ALTER TABLE guest_products VALIDATE CONSTRAINT fk_guest_products_transaction_service;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_entitlements_company') THEN
        ALTER TABLE guest_entitlements ADD CONSTRAINT fk_guest_entitlements_company FOREIGN KEY (company_id) REFERENCES company(id) NOT VALID;
    END IF;
    ALTER TABLE guest_entitlements VALIDATE CONSTRAINT fk_guest_entitlements_company;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_entitlements_client') THEN
        ALTER TABLE guest_entitlements ADD CONSTRAINT fk_guest_entitlements_client FOREIGN KEY (client_id) REFERENCES clients(id) NOT VALID;
    END IF;
    ALTER TABLE guest_entitlements VALIDATE CONSTRAINT fk_guest_entitlements_client;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_entitlements_product') THEN
        ALTER TABLE guest_entitlements ADD CONSTRAINT fk_guest_entitlements_product FOREIGN KEY (product_id) REFERENCES guest_products(id) NOT VALID;
    END IF;
    ALTER TABLE guest_entitlements VALIDATE CONSTRAINT fk_guest_entitlements_product;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_entitlements_source_order') THEN
        ALTER TABLE guest_entitlements ADD CONSTRAINT fk_guest_entitlements_source_order FOREIGN KEY (source_order_id) REFERENCES guest_orders(id) NOT VALID;
    END IF;
    ALTER TABLE guest_entitlements VALIDATE CONSTRAINT fk_guest_entitlements_source_order;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_entitlement_usages_entitlement') THEN
        ALTER TABLE guest_entitlement_usages ADD CONSTRAINT fk_guest_entitlement_usages_entitlement FOREIGN KEY (entitlement_id) REFERENCES guest_entitlements(id) NOT VALID;
    END IF;
    ALTER TABLE guest_entitlement_usages VALIDATE CONSTRAINT fk_guest_entitlement_usages_entitlement;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_entitlement_usages_session') THEN
        ALTER TABLE guest_entitlement_usages ADD CONSTRAINT fk_guest_entitlement_usages_session FOREIGN KEY (session_booking_id) REFERENCES session_booking(id) NOT VALID;
    END IF;
    ALTER TABLE guest_entitlement_usages VALIDATE CONSTRAINT fk_guest_entitlement_usages_session;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_notifications_guest_user') THEN
        ALTER TABLE guest_notifications ADD CONSTRAINT fk_guest_notifications_guest_user FOREIGN KEY (guest_user_id) REFERENCES guest_users(id) ON DELETE CASCADE NOT VALID;
    END IF;
    ALTER TABLE guest_notifications VALIDATE CONSTRAINT fk_guest_notifications_guest_user;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_notifications_company') THEN
        ALTER TABLE guest_notifications ADD CONSTRAINT fk_guest_notifications_company FOREIGN KEY (company_id) REFERENCES company(id) NOT VALID;
    END IF;
    ALTER TABLE guest_notifications VALIDATE CONSTRAINT fk_guest_notifications_company;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_guest_notifications_client') THEN
        ALTER TABLE guest_notifications ADD CONSTRAINT fk_guest_notifications_client FOREIGN KEY (client_id) REFERENCES clients(id) NOT VALID;
    END IF;
    ALTER TABLE guest_notifications VALIDATE CONSTRAINT fk_guest_notifications_client;
END $$;


-- ============================================================================
-- Squashed from V7__course_access_progress.sql
-- ============================================================================

CREATE TABLE IF NOT EXISTS course_access_progress (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    entitlement_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    position_seconds INTEGER NOT NULL DEFAULT 0,
    duration_seconds INTEGER,
    progress_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    last_played_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_course_access_progress_entitlement_course UNIQUE (entitlement_id, course_id),
    CONSTRAINT fk_course_access_progress_entitlement FOREIGN KEY (entitlement_id) REFERENCES guest_entitlements(id) ON DELETE CASCADE,
    CONSTRAINT fk_course_access_progress_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_course_access_progress_entitlement ON course_access_progress(entitlement_id);
CREATE INDEX IF NOT EXISTS idx_course_access_progress_course ON course_access_progress(course_id);

-- backend/src/main/java/com/example/app/delivery/MessageDeliveryLog.java
CREATE TABLE IF NOT EXISTS message_delivery_logs (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    company_id BIGINT NOT NULL REFERENCES company(id),
    client_id BIGINT REFERENCES clients(id),
    guest_user_id BIGINT,
    channel VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    message_type VARCHAR(80) NOT NULL,
    recipient VARCHAR(320),
    subject VARCHAR(500),
    message_preview VARCHAR(1200),
    reference_type VARCHAR(80),
    reference_id VARCHAR(80),
    provider_message_id VARCHAR(255),
    provider_status_code VARCHAR(80),
    error_message VARCHAR(1200),
    retry_count INTEGER NOT NULL DEFAULT 0,
    sent_at TIMESTAMP(6) WITH TIME ZONE,
    delivered_at TIMESTAMP(6) WITH TIME ZONE,
    failed_at TIMESTAMP(6) WITH TIME ZONE,
    metadata_json TEXT
);

CREATE INDEX IF NOT EXISTS idx_message_delivery_company_created
    ON message_delivery_logs(company_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_message_delivery_company_status
    ON message_delivery_logs(company_id, status);

CREATE INDEX IF NOT EXISTS idx_message_delivery_company_channel
    ON message_delivery_logs(company_id, channel);

CREATE INDEX IF NOT EXISTS idx_message_delivery_reference
    ON message_delivery_logs(company_id, reference_type, reference_id);


-- ============================================================================
-- Scheduled job run tracking
-- ============================================================================

CREATE TABLE IF NOT EXISTS scheduled_job_runs (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    job_name VARCHAR(120) NOT NULL,
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE,
    duration_ms BIGINT,
    instance_id VARCHAR(160),
    locked_by VARCHAR(160),
    records_processed INTEGER,
    error_message TEXT
);

CREATE INDEX IF NOT EXISTS idx_scheduled_job_runs_job_started
    ON scheduled_job_runs (job_name, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_scheduled_job_runs_status_started
    ON scheduled_job_runs (status, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_scheduled_job_runs_created
    ON scheduled_job_runs (created_at);

CREATE TABLE IF NOT EXISTS scheduled_job_alert_states (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    job_name VARCHAR(120) NOT NULL,
    alert_type VARCHAR(48) NOT NULL,
    status VARCHAR(32) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    first_detected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_detected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at TIMESTAMP WITH TIME ZONE,
    last_email_sent_at TIMESTAMP WITH TIME ZONE,
    last_recovery_email_sent_at TIMESTAMP WITH TIME ZONE,
    last_run_id BIGINT,
    message TEXT
);

CREATE INDEX IF NOT EXISTS idx_scheduled_job_alert_states_status
    ON scheduled_job_alert_states (status, last_detected_at DESC);

CREATE INDEX IF NOT EXISTS idx_scheduled_job_alert_states_job_status
    ON scheduled_job_alert_states (job_name, status);

CREATE INDEX IF NOT EXISTS idx_scheduled_job_alert_states_job_type_status
    ON scheduled_job_alert_states (job_name, alert_type, status);
