package com.example.app.guest.model;

public enum GuestNotificationType {
    BOOKING_CONFIRMED,
    BOOKING_RESCHEDULED,
    BOOKING_CANCELLED,
    BOOKING_UPDATED,
    BOOKING_REMINDER,
    BOOKING_FOLLOW_UP,
    ENTITLEMENT_ADDED,
    ENTITLEMENT_REMOVED,
    INVOICE_CREATED,
    PAYMENT_PENDING,
    PAYMENT_CONFIRMED,
    ANNOUNCEMENT,
    GUEST_MESSAGE
}
