import '../styles/features/clients-and-detail.css'
import '../styles/features/modern-clients.css'
import '../styles/calendar/calendar-shell.css'
import '../styles/calendar/calendar-events.css'
import '../styles/calendar/calendar-responsive.css'
import '../styles/main/calendar-popup.css'
import '../styles/main/calendar-popup-final.css'
import '../styles/main/calendar-booking-mode.css'
import '../styles/main/calendar-side-panel-system.css'

export { default } from './calendar/CalendarPageContent'
