import '../styles/features.booking.css'
import '../styles/features/booking-side-panel.css'
import '../styles/features/modern-clients.css'
import '../styles/features/meeting-provider.css'
import '../styles/calendar/calendar-shell.css'
import '../styles/calendar/calendar-events.css'
import '../styles/calendar/calendar-responsive.css'
import '../styles/main/calendar-popup.css'
import '../styles/main/calendar-popup-final.css'
import '../styles/main/calendar-booking-mode.css'

export { default } from './calendar/CalendarPageContent'
