package com.example.app.settings;

public enum SettingKey {
    SPACES_ENABLED,
    TYPES_ENABLED,
    BOOKABLE_ENABLED,
    ONLINE_SESSION_BOOKING_ENABLED,
    MODULE_CONFIG_TYPE,
    AI_BOOKING_ENABLED,
    /** Personal time blocks on the calendar (and personal-task presets tab). */
    PERSONAL_ENABLED,
    /** To-do items on the calendar and header task list. */
    TODOS_ENABLED,
    MULTIPLE_SESSIONS_PER_SPACE_ENABLED,
    MULTIPLE_CLIENTS_PER_SESSION_ENABLED,
    GROUP_BOOKING_ENABLED,
    BILLING_ENABLED,
    BILLING_INVOICES_ENABLED,
    BILLING_ONLINE_CARD_PAYMENTS_ENABLED,
    BILLING_BANK_TRANSFER_ENABLED,
    BILLING_PAYPAL_ENABLED,
    BILLING_GIFT_CARDS_ENABLED,
    COMMUNICATION_ENABLED,
    NOTIFICATIONS_ENABLED,
    NOTIFICATIONS_EMAIL_ALERTS_ENABLED,
    NOTIFICATIONS_SMS_ALERTS_ENABLED,
    NOTIFICATIONS_REMINDER_TEMPLATES_ENABLED,
    GOOGLE_CALENDAR_MODULE_ENABLED,
    WHATSAPP_MODULE_ENABLED,
    VIBER_MODULE_ENABLED,
    SECURITY_MODULE_ENABLED,
    SECURITY_SESSION_SECURITY_ENABLED,
    SECURITY_PASSKEYS_ENABLED,
    SECURITY_API_INTEGRATIONS_ENABLED,
    SESSION_LENGTH_MINUTES,
    WORKING_HOURS_START,
    WORKING_HOURS_END,
    PERSONAL_TASK_PRESETS_JSON,
    INVOICE_COUNTER,
    ORDER_COUNTER,

    COMPANY_NAME,
    COMPANY_ADDRESS,
    COMPANY_POSTAL_CODE,
    COMPANY_CITY,
    COMPANY_VAT_ID,
    COMPANY_IBAN,
    COMPANY_BIC,
    COMPANY_EMAIL,
    COMPANY_TELEPHONE,
    BANK_QR_PURPOSE_CODE,
    BANK_QR_PURPOSE_TEXT,
    /** JSON array of company profiles shown in Configuration -> Account Management -> Company. */
    COMPANY_PROFILES,
    /** Currently selected company profile id in Configuration -> Account Management -> Company. */
    COMPANY_SELECTED_PROFILE_ID,
    FISCAL_ENVIRONMENT,
    FISCAL_TAX_NUMBER,
    FISCAL_BUSINESS_PREMISE_ID,
    FISCAL_DEVICE_ID,
    FISCAL_SOFTWARE_SUPPLIER_TAX_NUMBER,
    FISCAL_CERTIFICATE_PASSWORD,
    FISCAL_CADASTRAL_NUMBER,
    FISCAL_BUILDING_NUMBER,
    FISCAL_BUILDING_SECTION_NUMBER,
    FISCAL_HOUSE_NUMBER,
    FISCAL_HOUSE_NUMBER_ADDITIONAL,
    FISCAL_TEST_INVOICE_URL,
    FISCAL_TEST_PREMISE_URL,
    FISCAL_PROD_INVOICE_URL,
    FISCAL_PROD_PREMISE_URL,
    FISCAL_REGISTERED_PREMISES_JSON,
    GLOBAL_FISCAL_TEST_INVOICE_URL,
    GLOBAL_FISCAL_TEST_PREMISE_URL,
    GLOBAL_FISCAL_PROD_INVOICE_URL,
    GLOBAL_FISCAL_PROD_PREMISE_URL,
    GLOBAL_MESSAGING_WHATSAPP_ENABLED,
    GLOBAL_MESSAGING_VIBER_ENABLED,
    GLOBAL_PAYMENTS_STRIPE_ENABLED,
    GLOBAL_PAYMENTS_PAYPAL_ENABLED,
    GLOBAL_AJPES_PRS_ENABLED,

    PAYMENT_DEADLINE_DAYS,
    ADVANCE_DEDUCTION_TRANSACTION_SERVICE_ID,
    /** Transaction service used when a booking participant is marked as NO SHOW. */
    NO_SHOW_TRANSACTION_SERVICE_ID,
    SIGNUP_PACKAGE_NAME,
    SIGNUP_USER_COUNT,
    SIGNUP_SMS_COUNT,
    SIGNUP_ADDON_KEYS,
    SIGNUP_FISCALIZATION_REQUIRED,
    /**
     * When {@code true}, the tenancy owner signed up without a password and must still complete the emailed setup link.
     * Cleared after they set a password via that flow.
     */
    SIGNUP_OWNER_PASSWORD_PENDING,

    /** Paid space quota for the tenancy (signup / billing). */
    TENANCY_SPACE_QUOTA,
    /** Cumulative outbound SMS parts successfully sent via the configured provider. */
    TENANCY_SMS_SENT_COUNT,
    BILLING_SUBSCRIPTION_START,
    BILLING_SUBSCRIPTION_END,
    /** MONTHLY or YEARLY */
    BILLING_SUBSCRIPTION_INTERVAL,
    /** User-seat quota planned for the next subscription billing period. */
    BILLING_SUBSCRIPTION_NEXT_USER_COUNT,
    /** SMS quota planned for the next subscription billing period. */
    BILLING_SUBSCRIPTION_NEXT_SMS_COUNT,
    /** Decimal amount string (e.g. EUR) still owed for subscription. */
    BILLING_SUBSCRIPTION_DUE_AMOUNT,
    /** Preferred payment method selected during self-serve signup billing details. */
    BILLING_SUBSCRIPTION_PAYMENT_METHOD,
    INVOICE_DELIVERY_EMAIL_ENABLED,
    INVOICE_DELIVERY_EMAIL_SUBJECT,
    INVOICE_DELIVERY_EMAIL_BODY,
    FOLIO_TEMPLATE_LAYOUT_JSON,
    COMPANY_LOGO_BASE64,
    FOLIO_SIGNATURE_BASE64,

    /** JSON: custom email/SMS templates and toggles for booking notifications (see frontend parser). */
    NOTIFICATION_SETTINGS_JSON,

    /** Inbox/omnichannel messaging settings. */
    INBOX_INFOBIP_BASE_URL,
    INBOX_INFOBIP_API_KEY,
    INBOX_WHATSAPP_SENDER,
    INBOX_VIBER_SENDER,
    INBOX_WHATSAPP_ACCESS_TOKEN,
    INBOX_WHATSAPP_PHONE_NUMBER_ID,
    INBOX_WHATSAPP_BUSINESS_ACCOUNT_ID,
    INBOX_WHATSAPP_WEBHOOK_VERIFY_TOKEN,
    INBOX_WHATSAPP_APP_SECRET,
    INBOX_VIBER_BOT_TOKEN,
    INBOX_VIBER_BOT_NAME,
    INBOX_VIBER_BOT_AVATAR_URL,

    /** Owner analytics digest settings. */
    ANALYTICS_REPORTS_ENABLED,
    ANALYTICS_REPORTS_EMAIL,
    ANALYTICS_REPORTS_FREQUENCY,
    ANALYTICS_REPORTS_LAST_SENT_AT,



    /** Guest app booking/payment behavior. */
    GUEST_BOOKING_RULES_JSON,

    /** Guest app public/discoverability settings. */
    GUEST_APP_SETTINGS_JSON,

    /**
     * JSON: public register page plan and add-on monthly prices (EUR), merged with built-in defaults.
     * Stored on the super-admin company that last saved it; public catalog picks the newest row by {@code updatedAt}.
     */
    PLATFORM_REGISTER_PRICE_JSON,

    /** Tenant PayPal seller onboarding and merchant configuration. */
    PAYPAL_MERCHANT_ID,
    PAYPAL_TRACKING_ID,
    PAYPAL_ONBOARDING_STATUS,

    /** Platform Stripe Connect configuration. Stored on the super-admin company and split by sandbox/production. */
    GLOBAL_STRIPE_SANDBOX_ENABLED,
    GLOBAL_STRIPE_SANDBOX_SECRET_KEY,
    GLOBAL_STRIPE_SANDBOX_PUBLISHABLE_KEY,
    GLOBAL_STRIPE_SANDBOX_WEBHOOK_SECRET,
    GLOBAL_STRIPE_SANDBOX_SUCCESS_URL,
    GLOBAL_STRIPE_SANDBOX_CANCEL_URL,
    GLOBAL_STRIPE_SANDBOX_CURRENCY,
    GLOBAL_STRIPE_SANDBOX_APPLICATION_FEE_PERCENT,
    GLOBAL_STRIPE_SANDBOX_APPLICATION_FEE_FIXED_MINOR,
    GLOBAL_STRIPE_PRODUCTION_ENABLED,
    GLOBAL_STRIPE_PRODUCTION_SECRET_KEY,
    GLOBAL_STRIPE_PRODUCTION_PUBLISHABLE_KEY,
    GLOBAL_STRIPE_PRODUCTION_WEBHOOK_SECRET,
    GLOBAL_STRIPE_PRODUCTION_SUCCESS_URL,
    GLOBAL_STRIPE_PRODUCTION_CANCEL_URL,
    GLOBAL_STRIPE_PRODUCTION_CURRENCY,
    GLOBAL_STRIPE_PRODUCTION_APPLICATION_FEE_PERCENT,
    GLOBAL_STRIPE_PRODUCTION_APPLICATION_FEE_FIXED_MINOR,

    /** Tenant Stripe Connect onboarding and connected-account status. */
    STRIPE_CONNECT_MODE,
    STRIPE_CONNECT_COUNTRY,
    STRIPE_CONNECT_BUSINESS_TYPE,
    STRIPE_SANDBOX_ACCOUNT_ID,
    STRIPE_SANDBOX_ONBOARDING_STATUS,
    STRIPE_SANDBOX_CHARGES_ENABLED,
    STRIPE_SANDBOX_PAYOUTS_ENABLED,
    STRIPE_SANDBOX_DETAILS_SUBMITTED,
    STRIPE_SANDBOX_REQUIREMENTS_JSON,
    STRIPE_PRODUCTION_ACCOUNT_ID,
    STRIPE_PRODUCTION_ONBOARDING_STATUS,
    STRIPE_PRODUCTION_CHARGES_ENABLED,
    STRIPE_PRODUCTION_PAYOUTS_ENABLED,
    STRIPE_PRODUCTION_DETAILS_SUBMITTED,
    STRIPE_PRODUCTION_REQUIREMENTS_JSON,

    /** Public widget security. */
    WIDGET_ALLOWED_ORIGINS,
    WIDGET_TURNSTILE_SITE_KEY,
    WIDGET_TURNSTILE_SECRET_KEY
}
