package com.example.app.settings;

public enum SettingKey {
    SPACES_ENABLED,
    TYPES_ENABLED,
    BOOKABLE_ENABLED,
    AI_BOOKING_ENABLED,
    /** Personal time blocks on the calendar (and personal-task presets tab). */
    PERSONAL_ENABLED,
    /** To-do items on the calendar and header task list. */
    TODOS_ENABLED,
    MULTIPLE_SESSIONS_PER_SPACE_ENABLED,
    MULTIPLE_CLIENTS_PER_SESSION_ENABLED,
    GROUP_BOOKING_ENABLED,
    SESSION_LENGTH_MINUTES,
    WORKING_HOURS_START,
    WORKING_HOURS_END,
    PERSONAL_TASK_PRESETS_JSON,
    INVOICE_COUNTER,

    COMPANY_NAME,
    COMPANY_ADDRESS,
    COMPANY_POSTAL_CODE,
    COMPANY_CITY,
    COMPANY_VAT_ID,
    COMPANY_IBAN,
    COMPANY_BIC,
    COMPANY_EMAIL,
    COMPANY_TELEPHONE,
    BANK_QR_PURPOSE_CODE,
    BANK_QR_PURPOSE_TEXT,
    FISCAL_ENVIRONMENT,
    FISCAL_TAX_NUMBER,
    FISCAL_BUSINESS_PREMISE_ID,
    FISCAL_DEVICE_ID,
    FISCAL_SOFTWARE_SUPPLIER_TAX_NUMBER,
    FISCAL_CERTIFICATE_PASSWORD,
    FISCAL_CADASTRAL_NUMBER,
    FISCAL_BUILDING_NUMBER,
    FISCAL_BUILDING_SECTION_NUMBER,
    FISCAL_HOUSE_NUMBER,
    FISCAL_HOUSE_NUMBER_ADDITIONAL,
    FISCAL_TEST_INVOICE_URL,
    FISCAL_TEST_PREMISE_URL,
    FISCAL_PROD_INVOICE_URL,
    FISCAL_PROD_PREMISE_URL,
    FISCAL_REGISTERED_PREMISES_JSON,
    GLOBAL_FISCAL_TEST_INVOICE_URL,
    GLOBAL_FISCAL_TEST_PREMISE_URL,

    PAYMENT_DEADLINE_DAYS,
    SIGNUP_PACKAGE_NAME,
    SIGNUP_USER_COUNT,
    SIGNUP_SMS_COUNT,
    SIGNUP_FISCALIZATION_REQUIRED,

    /** Paid space quota for the tenancy (signup / billing). */
    TENANCY_SPACE_QUOTA,
    /** Cumulative reminder SMS successfully sent (Infobip). */
    TENANCY_SMS_SENT_COUNT,
    BILLING_SUBSCRIPTION_START,
    BILLING_SUBSCRIPTION_END,
    /** MONTHLY or YEARLY */
    BILLING_SUBSCRIPTION_INTERVAL,
    /** Decimal amount string (e.g. EUR) still owed for subscription. */
    BILLING_SUBSCRIPTION_DUE_AMOUNT,
    FOLIO_TEMPLATE_LAYOUT_JSON,
    COMPANY_LOGO_BASE64,
    FOLIO_SIGNATURE_BASE64,

    /** JSON: custom email/SMS templates and toggles for booking notifications (see frontend parser). */
    NOTIFICATION_SETTINGS_JSON,

    /** Inbox/omnichannel messaging settings. */
    INBOX_INFOBIP_BASE_URL,
    INBOX_INFOBIP_API_KEY,
    INBOX_WHATSAPP_SENDER,
    INBOX_VIBER_SENDER,
    INBOX_WHATSAPP_ACCESS_TOKEN,
    INBOX_WHATSAPP_PHONE_NUMBER_ID,
    INBOX_WHATSAPP_BUSINESS_ACCOUNT_ID,
    INBOX_WHATSAPP_WEBHOOK_VERIFY_TOKEN,
    INBOX_WHATSAPP_APP_SECRET,
    INBOX_VIBER_BOT_TOKEN,
    INBOX_VIBER_BOT_NAME,
    INBOX_VIBER_BOT_AVATAR_URL,

    /** Owner analytics digest settings. */
    ANALYTICS_REPORTS_ENABLED,
    ANALYTICS_REPORTS_EMAIL,
    ANALYTICS_REPORTS_FREQUENCY,
    ANALYTICS_REPORTS_LAST_SENT_AT,



    /** Guest app booking/payment behavior. */
    GUEST_BOOKING_RULES_JSON,

    /** Guest app public/discoverability settings. */
    GUEST_APP_SETTINGS_JSON,

    /** Tenant PayPal seller onboarding and merchant configuration. */
    PAYPAL_MERCHANT_ID,
    PAYPAL_TRACKING_ID,
    PAYPAL_ONBOARDING_STATUS,

    /** Public widget security. */
    WIDGET_ALLOWED_ORIGINS,
    WIDGET_TURNSTILE_SITE_KEY,
    WIDGET_TURNSTILE_SECRET_KEY
}
