#!/usr/bin/env python3
"""Regenerate the Phase 4 mutating-endpoint inventory after an audit review.

Run from the repository root:
    python scripts/generate-activity-audit-endpoints.py

The resulting snapshot is intentionally committed. Any POST/PUT/PATCH/DELETE
controller change then becomes a CI-visible event that must be reviewed for
ActivityLog coverage (or deliberately documented as non-business/technical).
"""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
JAVA_ROOT = ROOT / "backend" / "src" / "main" / "java" / "com" / "example" / "app"
OUT = ROOT / "backend" / "src" / "test" / "resources" / "activity-audit" / "mutation-endpoints.txt"
MAPPING_NAMES = ("PostMapping", "PutMapping", "PatchMapping", "DeleteMapping")
MAPPING_RE = re.compile(r"@(PostMapping|PutMapping|PatchMapping|DeleteMapping)\b")
METHOD_RE = re.compile(r"\bpublic\s+(?:[\w$<>?,.\[\]@]+\s+)+([A-Za-z_$][A-Za-z0-9_$]*)\s*\(")


def paren_balance(text: str) -> int:
    return text.count("(") - text.count(")")


def normalize(text: str) -> str:
    return re.sub(r"\s+", "", text.strip())


def extract_file(path: Path):
    lines = path.read_text(encoding="utf-8").splitlines()
    entries = []
    i = 0
    while i < len(lines):
        match = MAPPING_RE.search(lines[i])
        if not match:
            i += 1
            continue
        mapping = match.group(1)
        annotation = lines[i].strip()
        balance = paren_balance(annotation)
        j = i
        while balance > 0 and j + 1 < len(lines):
            j += 1
            annotation += " " + lines[j].strip()
            balance += paren_balance(lines[j])

        k = j + 1
        declaration = ""
        method_name = None
        while k < min(len(lines), j + 80):
            stripped = lines[k].strip()
            if stripped.startswith("@") and not declaration:
                k += 1
                continue
            if "public " in stripped or declaration:
                declaration += " " + stripped
                m = METHOD_RE.search(declaration)
                if m:
                    method_name = m.group(1)
                    break
                if "{" in stripped and "(" not in declaration:
                    break
            k += 1
        if method_name is None:
            raise RuntimeError(f"Could not resolve method after @{mapping} in {path}:{i + 1}")

        rel = path.relative_to(JAVA_ROOT).as_posix()
        entries.append(f"{rel}|{normalize(annotation)}|{method_name}")
        i = j + 1
    return entries


def main():
    entries = []
    for path in sorted(JAVA_ROOT.rglob("*Controller.java")):
        entries.extend(extract_file(path))
    entries = sorted(set(entries))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "# Calendra mutating HTTP endpoint inventory.\n"
        "# Generated by scripts/generate-activity-audit-endpoints.py after manual ActivityLog review.\n"
        "# Format: relative controller path|normalized mapping annotation|method name\n"
        + "\n".join(entries)
        + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(entries)} mutation endpoints to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise
